---
language: ruby
before_script:
  - "bundle exec puppet module install adrien/boolean"
  - "bundle exec puppet module install adrien/filemapper"
script: "spec/travis_rspec.rb --color --format documentation -I $(puppet module list | head -n1)/filemapper/lib"
notifications:
  email: false
rvm:
  - 1.9.3
  - 1.8.7
